apiVersion: v1
kind: Service
metadata:
  name: flink
  namespace: winter
spec:
  selector:
    app: flink
    component: jobmanager  
  type: LoadBalancer
  ports:
    - nodePort: 30021
      port: 8081
      protocol: TCP
      targetPort: 8081
  sessionAffinity: ClientIP

